services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # so you can connect from local
    environment:
      POSTGRES_PASSWORD: objets
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      # do not mount host system node_modules
      # cf https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: objets
      MAILHOG_HOST: mailhog
  worker:
    build: .
    command: bundle exec good_job start
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: objets
      MAILHOG_HOST: mailhog
  vite_dev:
    build: .
    command: bundle exec vite dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  node_modules:
  postgres_data:
