apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: collectif-objets-dev-config
build:
  artifacts:
  - image: collectif-objets-prod-distroless
    context: ..
    docker:
      dockerfile: k8s/image_build/Dockerfile.prod.distroless
  - image: collectif-objets-dev
    context: ..
    docker:
      dockerfile: k8s/image_build/Dockerfile.dev
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  rawYaml:
  - db-deployment.yaml
  - db-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - worker-deployment.yaml
  - rails-db-init-job.yaml
